project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

from base.views import debug as debug_views
from base.views import misc as misc_views

debug_patterns = [
    path("request/", debug_views.HttpRequestPrintView.as_view(), name="debug-request"),
]

urlpatterns = [
    path("admin/", include("loginas.urls")),
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("debug/", include(debug_patterns)),
    path("regions/", include("regions.urls")),
    path("status/", misc_views.StatusView.as_view(), name="status"),
    path("api/v1/", include("dummy_app.urls")),
    path("", misc_views.IndexView.as_view(), name="home"),
    path("", include("documents.urls")),
    path("", include("information_assets.urls")),
    path("risks/", include("risks.urls")),
    path("", include("processes.urls")),
    path("", include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    if not settings.TEST:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    if settings.ENABLE_DEBUG_TOOLBAR:
        # others libraries
        import debug_toolbar

        urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

elif settings.LOCAL_PROD_TESTING:
    # For simplicity, use the development server to serve static and media,
    # even with DEBUG=False.

    # "static(...)" is a no-op when DEBUG is False. So work around that guard:
    original_debug = settings.DEBUG
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    settings.DEBUG = original_debug


# custom error views
handler400 = "base.views.misc.bad_request_view"
handler403 = "base.views.misc.permission_denied_view"
handler404 = "base.views.misc.page_not_found_view"
handler500 = "base.views.misc.server_error_view"

risks/urls.py
from django.urls import path

from risks.views import risk as risk_views

urlpatterns = [
    path(
        "",
        risk_views.RiskListView.as_view(),
        name="risk_list",
    ),
    path(
        "create/",
        risk_views.RiskCreateView.as_view(),
        name="risk_create",
    ),
    path(
        "<int:pk>/",
        risk_views.RiskDetailView.as_view(),
        name="risk_detail",
    ),
    path(
        "<int:pk>/update/",
        risk_views.RiskUpdateView.as_view(),
        name="risk_update",
    ),
    path(
        "<int:pk>/delete/",
        risk_views.RiskDeleteView.as_view(),
        name="risk_delete",
    ),
]

risks/models/risk.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from base.models import BaseModel
from documents.models.control import Control
from information_assets.models.asset import Asset
from risks.enums import LikelihoodChoices
from risks.enums import SeverityChoices
from risks.enums import TreatmentChoices
from risks.managers import RiskQuerySet


class Risk(BaseModel):
    assets = models.ManyToManyField(
        Asset, verbose_name=_("asset"), related_name="risks"
    )
    controls = models.ManyToManyField(
        Control,
        verbose_name=_("control"),
        related_name="risks",
        blank=True,
    )
    title = models.CharField(verbose_name=_("title"), max_length=255, unique=True)
    description = models.TextField(verbose_name=_("description"), blank=True)
    responsible = models.ForeignKey(
        verbose_name=_("responsible"),
        to=settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="risks",
    )
    severity = models.CharField(
        verbose_name=_("severity"), max_length=255, choices=SeverityChoices.choices
    )
    likelihood = models.CharField(
        verbose_name=_("likelihood"), max_length=255, choices=LikelihoodChoices.choices
    )
    treatment = models.CharField(
        verbose_name=_("treatment"), max_length=255, choices=TreatmentChoices.choices
    )
    residual_risks = models.ManyToManyField(
        "self",
        verbose_name=_("residual risk for"),
        related_name="residual_risk_for",
        symmetrical=False,
        blank=True,
    )

    objects = RiskQuerySet.as_manager()

    class Meta:
        verbose_name = _("risk")
        verbose_name_plural = _("risks")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("risk_detail", args=(self.pk,))

risks/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from base.forms import BaseModelForm
from risks.models.risk import Risk


class RiskForm(BaseModelForm):
    residual_risk_for = forms.ModelMultipleChoiceField(
        queryset=Risk.objects.all(),
        required=False,
        label=_("Residual risk for"),
    )

    class Meta:
        model = Risk
        fields = (
            "assets",
            "controls",
            "title",
            "description",
            "responsible",
            "severity",
            "likelihood",
            "treatment",
            "residual_risk_for",
        )

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields["responsible"].label_from_instance = lambda user: user.get_label()
        if self.instance.pk is not None:
            residual_risk_for_field = self.fields["residual_risk_for"]
            residual_risk_for_field.queryset = (
                Risk.objects.get_residual_risk_for_queryset(self.instance)
            )
            residual_risk_for_field.initial = self.instance.residual_risk_for.all()

    def save(self, commit: bool = True) -> Risk:
        instance = super().save(commit)
        if not commit:
            return instance
        instance.residual_risk_for.set(self.cleaned_data["residual_risk_for"])
        return instance

risks/views/risk.py
from base.views.generic import BaseCreateView
from base.views.generic import BaseDeleteView
from base.views.generic import BaseDetailView
from base.views.generic import BaseListView
from base.views.generic import BaseUpdateView

from ..forms import RiskForm
from ..models.risk import Risk


class RiskListView(BaseListView):
    model = Risk
    template_name = "risks/risk/list.html"
    permission_required = "risks.view_risk"


class RiskCreateView(BaseCreateView):
    model = Risk
    form_class = RiskForm
    template_name = "risks/risk/create.html"
    permission_required = "risks.add_risk"


class RiskDetailView(BaseDetailView):
    model = Risk
    template_name = "risks/risk/detail.html"
    permission_required = "risks.view_risk"


class RiskUpdateView(BaseUpdateView):
    model = Risk
    form_class = RiskForm
    template_name = "risks/risk/update.html"
    permission_required = "risks.change_risk"


class RiskDeleteView(BaseDeleteView):
    model = Risk
    permission_required = "risks.delete_risk"
    template_name = "risks/risk/delete.html"

risks/templates/risks/risk/create.html
{% extends "form.html" %}

{% load i18n %}

{% block breadcrumbs %}
  <li class="breadcrumb-item">
    <a href="{% url 'risk_list' %}">{{ opts.verbose_name_plural|capfirst }}</a>
  </li>
{% endblock breadcrumbs %}

risks/templates/risks/risk/delete.html
{% extends "base.html" %}

{% load i18n %}

{% block breadcrumbs %}
  <li class="breadcrumb-item">
    <a href="{% url 'risk_list' %}">{{ opts.verbose_name_plural|capfirst }}</a>
  </li>
  <li class="breadcrumb-item">
    <a href="{{ object.get_absolute_url }}">{{ object }}</a>
  </li>
{% endblock breadcrumbs %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <div class="alert alert-danger">
      {% blocktrans %}Are you sure you want to delete "{{ object }}"?{% endblocktrans %}
    </div>
    <div class="text-end">
      <div class="btn-group">
        <input class="btn btn-danger" type="submit" value='{% trans "Confirm" %}'>
        <a class="btn btn-outline-secondary"
           href="{{ object.get_absolute_url }}">{% trans "Cancel" %}</a>
      </div>
    </div>
  </form>
{% endblock content %}

risks/templates/risks/risk/detail.html
{% extends "base.html" %}

{% load i18n %}

{% block options %}
  {% if perms.risks.change_risk %}
    <a class="btn btn-sm btn-outline-secondary"
       href="{% url 'risk_update' risk.id %}">
      {% trans "Update risk" %}
      <i class="fa fa-edit"></i>
    </a>
  {% endif %}
  {% if perms.risks.delete_risk %}
    <a class="btn btn-sm btn-danger" href="{% url 'risk_delete' risk.id %}">
      {% trans "Delete risk" %}
      <i class="fa fa-times"></i>
    </a>
  {% endif %}
{% endblock options %}

{% block breadcrumbs %}
  <li class="breadcrumb-item">
    <a href="{% url 'risk_list' %}">{{ opts.verbose_name_plural|capfirst }}</a>
  </li>
{% endblock breadcrumbs %}

{% block content %}
  <table class="table table-striped table-hover table-sm">
    <tbody>
      <tr>
        <th>{% trans "title"|capfirst %}</th>
        <td>{{ risk.title }}</td>
      </tr>
      <tr>
        <th>{% trans "description"|capfirst %}</th>
        <td>{{ risk.description|linebreaks }}</td>
      </tr>
      <tr>
        <th>{% trans "responsible"|capfirst %}</th>
        <td>{{ risk.responsible.get_label }}</td>
      </tr>
      <tr>
        <th>{% trans "severity"|capfirst %}</th>
        <td>{{ risk.get_severity_display }}</td>
      </tr>
      <tr>
        <th>{% trans "likelihood"|capfirst %}</th>
        <td>{{ risk.get_likelihood_display }}</td>
      </tr>
      <tr>
        <th>{% trans "treatment"|capfirst %}</th>
        <td>{{ risk.get_treatment_display }}</td>
      </tr>
      <tr>
        <th>{% trans "created at"|capfirst %}</th>
        <td>{{ risk.created_at }}</td>
      </tr>
      <tr>
        <th>{% trans "created by"|capfirst %}</th>
        <td>{{ risk.created_by.get_label }}</td>
      </tr>
      <tr>
        <th>{% trans "updated at"|capfirst %}</th>
        <td>{{ risk.updated_at }}</td>
      </tr>
      <tr>
        <th>{% trans "updated by"|capfirst %}</th>
        <td>{{ risk.updated_by.get_label }}</td>
      </tr>
    </tbody>
  </table>
  <br>
  <h2>{% trans "assets"|capfirst %}</h2>
  {% include "information_assets/includes/asset_table.html" with object_list=risk.assets.all %}
  <br>
  <h2>{% trans "controls"|capfirst %}</h2>
  {% include "documents/includes/control_table.html" with object_list=risk.controls.all %}
  <br>
  <h2>{% trans "residual risks"|capfirst %}</h2>
  {% include "risks/includes/risk_table.html" with object_list=risk.residual_risks.all %}
  <br>
  <h2>{% trans "residual risk for"|capfirst %}</h2>
  {% include "risks/includes/risk_table.html" with object_list=risk.residual_risk_for.all %}
{% endblock content %}

risks/templates/risks/risk/list.html
{% extends "base.html" %}

{% load i18n %}

{% block options %}
  {% if perms.risks.add_risk %}
    <a class="btn btn-sm btn-outline-secondary"
       href="{% url 'risk_create' %}">
      {% trans "Add risk" %}
      <i class="fa fa-plus"></i>
    </a>
  {% endif %}
{% endblock options %}

{% block content %}
  {% include "risks/includes/risk_table.html" %}
  {% include "includes/pagination.html" %}
{% endblock content %}

risks/templates/risks/risk/update.html
{% extends "form.html" %}

{% load i18n %}

{% block breadcrumbs %}
  <li class="breadcrumb-item">
    <a href="{% url 'risk_list' %}">{{ opts.verbose_name_plural|capfirst }}</a>
  </li>
  <li class="breadcrumb-item">
    <a href="{{ object.get_absolute_url }}">{{ object }}</a>
  </li>
{% endblock breadcrumbs %}