processes/urls.py
from django.urls import include
from django.urls import path

from processes.views import process as process_views
from processes.views import process_activity as processactivity_views
from processes.views import process_activity_instance as processactivityinstance_views
from processes.views import process_instance as processinstance_views
from processes.views import process_version as processversion_views

process_urlpatterns = [
    path(
        "",
        process_views.ProcessListView.as_view(),
        name="process_list",
    ),
    path(
        "create/",
        process_views.ProcessCreateView.as_view(),
        name="process_create",
    ),
    path(
        "<int:pk>/",
        process_views.ProcessDetailView.as_view(),
        name="process_detail",
    ),
    path(
        "<int:pk>/update/",
        process_views.ProcessUpdateView.as_view(),
        name="process_update",
    ),
    path(
        "<int:pk>/delete/",
        process_views.ProcessDeleteView.as_view(),
        name="process_delete",
    ),
]

processversion_urlpatterns = [
    path(
        "<int:parent_pk>/versions/create/",
        processversion_views.ProcessVersionCreateView.as_view(),
        name="processversion_create",
    ),
    path(
        "versions/<int:pk>/",
        processversion_views.ProcessVersionDetailView.as_view(),
        name="processversion_detail",
    ),
    path(
        "versions/<int:pk>/update/",
        processversion_views.ProcessVersionUpdateView.as_view(),
        name="processversion_update",
    ),
    path(
        "versions/<int:pk>/delete/",
        processversion_views.ProcessVersionDeleteView.as_view(),
        name="processversion_delete",
    ),
    path(
        "versions/<int:pk>/publish/",
        processversion_views.ProcessVersionPublishView.as_view(),
        name="processversion_publish",
    ),
    path(
        "versions/<int:parent_pk>/activities/create/",
        processactivity_views.ProcessActivityCreateView.as_view(),
        name="processactivity_create",
    ),
]

processinstance_urlpatterns = [
    path(
        "",
        processinstance_views.ProcessInstanceListView.as_view(),
        name="processinstance_list",
    ),
    path(
        "create/",
        processinstance_views.ProcessInstanceCreateView.as_view(),
        name="processinstance_create",
    ),
    path(
        "<int:pk>/",
        processinstance_views.ProcessInstanceDetailView.as_view(),
        name="processinstance_detail",
    ),
    path(
        "<int:pk>/delete/",
        processinstance_views.ProcessInstanceDeleteView.as_view(),
        name="processinstance_delete",
    ),
]

processactivity_urlpatterns = [
    path(
        "<int:pk>/",
        processactivity_views.ProcessActivityDetailView.as_view(),
        name="processactivity_detail",
    ),
    path(
        "<int:pk>/update/",
        processactivity_views.ProcessActivityUpdateView.as_view(),
        name="processactivity_update",
    ),
    path(
        "<int:pk>/delete/",
        processactivity_views.ProcessActivityDeleteView.as_view(),
        name="processactivity_delete",
    ),
]

processactivityinstance_urlpatterns = [
    path(
        "<int:pk>/",
        processactivityinstance_views.ProcessActivityInstanceDetailView.as_view(),
        name="processactivityinstance_detail",
    ),
    path(
        "<int:pk>/complete/",
        processactivityinstance_views.ProcessActivityInstanceCompleteView.as_view(),
        name="processactivityinstance_complete",
    ),
]

urlpatterns = [
    path("processes/", include(process_urlpatterns)),
    path("processes/", include(processversion_urlpatterns)),
    path("process-instances/", include(processinstance_urlpatterns)),
    path("activities/", include(processactivity_urlpatterns)),
    path("activity-instances/", include(processactivityinstance_urlpatterns)),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

from base.views import debug as debug_views
from base.views import misc as misc_views

debug_patterns = [
    path("request/", debug_views.HttpRequestPrintView.as_view(), name="debug-request"),
]

urlpatterns = [
    path("admin/", include("loginas.urls")),
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("debug/", include(debug_patterns)),
    path("regions/", include("regions.urls")),
    path("status/", misc_views.StatusView.as_view(), name="status"),
    path("api/v1/", include("dummy_app.urls")),
    path("", misc_views.IndexView.as_view(), name="home"),
    path("", include("documents.urls")),
    path("", include("information_assets.urls")),
    path("risks/", include("risks.urls")),
    path("", include("processes.urls")),
    path("", include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    if not settings.TEST:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    if settings.ENABLE_DEBUG_TOOLBAR:
        # others libraries
        import debug_toolbar

        urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

elif settings.LOCAL_PROD_TESTING:
    # For simplicity, use the development server to serve static and media,
    # even with DEBUG=False.

    # "static(...)" is a no-op when DEBUG is False. So work around that guard:
    original_debug = settings.DEBUG
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    settings.DEBUG = original_debug


# custom error views
handler400 = "base.views.misc.bad_request_view"
handler403 = "base.views.misc.permission_denied_view"
handler404 = "base.views.misc.page_not_found_view"
handler500 = "base.views.misc.server_error_view"

risks/urls.py
from django.urls import path

from risks.views import risk as risk_views

urlpatterns = [
    path(
        "",
        risk_views.RiskListView.as_view(),
        name="risk_list",
    ),
    path(
        "create/",
        risk_views.RiskCreateView.as_view(),
        name="risk_create",
    ),
    path(
        "<int:pk>/",
        risk_views.RiskDetailView.as_view(),
        name="risk_detail",
    ),
    path(
        "<int:pk>/update/",
        risk_views.RiskUpdateView.as_view(),
        name="risk_update",
    ),
    path(
        "<int:pk>/delete/",
        risk_views.RiskDeleteView.as_view(),
        name="risk_delete",
    ),
]

processes/models/process_activity.py
from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from base.models.base_model import BaseModel
from base.models.increment_field_mixin import IncrementFieldModelBase
from users.models.group import Group

if TYPE_CHECKING:
    from processes.models.process_activity_instance import ProcessActivityInstance
    from processes.models.process_instance import ProcessInstance
    from users.models.user import User


class ProcessActivity(IncrementFieldModelBase, BaseModel):
    process_version = models.ForeignKey(
        verbose_name=_("process version"),
        to="ProcessVersion",
        on_delete=models.PROTECT,
        related_name="activities",
    )
    order = models.PositiveIntegerField(verbose_name=_("order"))
    title = models.CharField(
        verbose_name=_("title"),
        max_length=255,
    )
    description = models.TextField(verbose_name=_("description"))
    assignee_groups = models.ManyToManyField(
        verbose_name=_("assignee groups"),
        to=Group,
        related_name="activities",
    )
    deliverables = models.TextField(
        verbose_name=_("deliverables"),
        blank=True,
    )
    email_to_notify = models.EmailField(
        verbose_name=_("email to notify"),
        blank=True,
    )

    class Meta:
        verbose_name = _("process activity")
        verbose_name_plural = _("process activities")
        ordering = ("process_version", "order")

    @property
    def can_be_updated(self) -> bool:
        return self.process_version.can_be_updated

    def __str__(self) -> str:
        return self.title

    def _get_increment_queryset(self) -> models.QuerySet[ProcessActivity]:
        return self.process_version.activities.all()

    def _get_field_to_increment(self) -> str:
        return "order"

    def create_instance(
        self, process_instance: ProcessInstance, assignee: User | None = None
    ) -> ProcessActivityInstance:
        from processes.models.process_activity_instance import ProcessActivityInstance

        if assignee is None:
            assignee = process_instance.created_by
        return ProcessActivityInstance.objects.create(
            process_instance=process_instance,
            activity=self,
            assignee=assignee,
        )

    def get_next_activity(self) -> ProcessActivity | None:
        qs = self.process_version.activities.filter(order__gt=self.order)
        if qs.exists():
            return qs.earliest("order")
        return None

    def get_absolute_url(self) -> str:
        return reverse("processactivity_detail", args=(self.pk,))

processes/models/process_definition.py
from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from base.models.base_model import BaseModel
from documents.models.control import Control
from processes.enums import TimeFrameChoices

if TYPE_CHECKING:
    from processes.models.process_instance import ProcessInstance


class ProcessDefinition(BaseModel):
    name = models.CharField(verbose_name=_("name"), max_length=255)
    control = models.ForeignKey(
        to=Control,
        on_delete=models.CASCADE,
        related_name="process_definitions",
        verbose_name=_("control"),
    )
    recurrency = models.CharField(
        verbose_name=_("recurrency"),
        max_length=255,
        choices=TimeFrameChoices.choices,
        blank=True,
    )

    class Meta:
        verbose_name = _("process definition")
        verbose_name_plural = _("process definitions")

    def __str__(self) -> str:
        return self.name

    def create_activities_for_process_instance(
        self, process_instance: ProcessInstance
    ) -> None:
        for activity in self.activities.all():
            activity.create_activity_for_process_instance(process_instance)

    def get_absolute_url(self) -> str:
        return reverse("processdefinition_detail", args=(self.pk,))

processes/models/process_version.py
from __future__ import annotations

from typing import TYPE_CHECKING

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from base.models.base_model import BaseModel
from base.models.version_mixin import VersionModelBase
from documents.models.control import Control
from documents.models.document import Document
from processes.enums import TimeFrameChoices
from processes.managers import ProcessVersionQuerySet
from processes.models.process import Process

if TYPE_CHECKING:
    from processes.models.process_instance import ProcessInstance
    from users.models.user import User


class ProcessVersion(VersionModelBase, BaseModel):
    process = models.ForeignKey(
        verbose_name=_("process"),
        to=Process,
        on_delete=models.PROTECT,
        related_name="versions",
    )
    defined_in = models.ForeignKey(
        verbose_name=_("defined in"),
        to=Document,
        on_delete=models.PROTECT,
        related_name="processes",
    )
    controls = models.ManyToManyField(
        verbose_name=_("controls"),
        to=Control,
        related_name="process_versions",
    )
    comment_label = models.CharField(
        verbose_name=_("comment label"),
        max_length=31,
        blank=True,
    )
    recurrency = models.CharField(
        verbose_name=_("recurrency"),
        max_length=255,
        choices=TimeFrameChoices.choices,
        blank=True,
    )
    email_to_notify_completion = models.EmailField(
        verbose_name=_("email to notify completion"),
        blank=True,
    )
    is_published = models.BooleanField(
        verbose_name=_("published"),
        default=False,
    )
    published_at = models.DateTimeField(
        verbose_name=_("published at"),
        null=True,
        blank=True,
    )
    published_by = models.ForeignKey(
        verbose_name=_("published by"),
        to=settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="published_process_versions",
        null=True,
        blank=True,
    )

    objects = ProcessVersionQuerySet.as_manager()

    class Meta:
        verbose_name = _("process version")
        verbose_name_plural = _("process versions")
        permissions = (("publish_processversion", "Can publish process version"),)

    @property
    def can_be_updated(self) -> bool:
        return not self.is_published

    def __str__(self) -> str:
        return f"{self.process} V{self.version}"

    def save(self, *args, **kwargs):
        adding = self._state.adding
        previous_version = self.process.last_published_version
        super().save(*args, **kwargs)
        self._copy_activities_from_previous_version(adding, previous_version)

    def _copy_activities_from_previous_version(
        self, adding: bool, previous_version: ProcessVersion
    ) -> None:
        if not adding or previous_version is None:
            return
        for activity in previous_version.activities.all():
            assignee_groups = tuple(activity.assignee_groups.all())
            activity.pk = None
            activity.process_version = self
            activity.save()
            activity.assignee_groups.set(assignee_groups)

    def _get_increment_queryset(self) -> models.QuerySet[ProcessVersion]:
        return self.process.versions.all()

    def create_first_activity_instance(self, process_instance: ProcessInstance) -> None:
        if self.activities.exists():
            self.activities.earliest("order").create_instance(process_instance)

    def get_absolute_url(self) -> str:
        return reverse("processversion_detail", args=(self.pk,))

    def publish(self, user: User) -> None:
        update_dict = {"is_published": True, "published_at": timezone.now()}
        if user and not user.is_anonymous:
            update_dict["published_by"] = user
        self.update(**update_dict)

processes/views/process.py
from base.views.generic.detail import BaseDetailView
from base.views.generic.edit import BaseCreateView
from base.views.generic.edit import BaseDeleteView
from base.views.generic.edit import BaseUpdateView
from base.views.generic.list import BaseListView
from processes.forms import ProcessForm
from processes.models.process import Process


class ProcessListView(BaseListView):
    model = Process
    template_name = "processes/process/list.html"
    permission_required = "processes.view_process"


class ProcessCreateView(BaseCreateView):
    model = Process
    form_class = ProcessForm
    template_name = "processes/process/create.html"
    permission_required = "processes.add_process"


class ProcessDetailView(BaseDetailView):
    model = Process
    template_name = "processes/process/detail.html"
    permission_required = "processes.view_process"


class ProcessUpdateView(BaseUpdateView):
    model = Process
    form_class = ProcessForm
    template_name = "processes/process/update.html"
    permission_required = "processes.change_process"


class ProcessDeleteView(BaseDeleteView):
    model = Process
    template_name = "processes/process/delete.html"
    permission_required = "processes.delete_process"

processes/views/process_activity.py
from base.views.generic.detail import BaseDetailView
from base.views.generic.edit import BaseDeleteView
from base.views.generic.edit import BaseSubModelCreateView
from base.views.generic.edit import BaseUpdateView
from base.views.generic.list import BaseListView
from processes.forms import ProcessActivityForm
from processes.models.process_activity import ProcessActivity
from processes.models.process_version import ProcessVersion


class ProcessActivityListView(BaseListView):
    model = ProcessActivity
    template_name = "processes/processactivity/list.html"
    permission_required = "processes.view_processactivity"


class ProcessActivityCreateView(BaseSubModelCreateView):
    model = ProcessActivity
    parent_model = ProcessVersion
    form_class = ProcessActivityForm
    template_name = "processes/processactivity/create.html"
    permission_required = "processes.add_processactivity"

    def get_parent_queryset(self):
        return super().get_parent_queryset().filter(is_published=False)


class ProcessActivityDetailView(BaseDetailView):
    model = ProcessActivity
    template_name = "processes/processactivity/detail.html"
    permission_required = "processes.view_processactivity"


class ProcessActivityUpdateView(BaseUpdateView):
    model = ProcessActivity
    form_class = ProcessActivityForm
    template_name = "processes/processactivity/update.html"
    permission_required = "processes.change_processactivity"

    def get_queryset(self):
        return super().get_queryset().filter(process_version__is_published=False)


class ProcessActivityDeleteView(BaseDeleteView):
    model = ProcessActivity
    template_name = "processes/processactivity/delete.html"
    permission_required = "processes.delete_processactivity"

    def get_queryset(self):
        return super().get_queryset().filter(process_version__is_published=False)

    def get_success_url(self):
        return self.object.process_version.get_absolute_url()

processes/templates/processes/processversion/create.html
{% extends "form.html" %}

{% load i18n %}

{% block breadcrumbs %}
  <li class="breadcrumb-item">
    <a href="{% url 'process_list' %}">{% trans "processes"|capfirst %}</a>
  </li>
  <li class="breadcrumb-item">
    <a href="{{ process.get_absolute_url }}">{{ process }}</a>
  </li>
{% endblock breadcrumbs %}

processes/templates/processes/processversion/delete.html
{% extends "base.html" %}

{% load i18n %}

{% block breadcrumbs %}
  <li class="breadcrumb-item">
    <a href="{% url 'process_list' %}">{% trans "processes"|capfirst %}</a>
  </li>
  <li class="breadcrumb-item">
    {% with process=object.process %}<a href="{{ process.get_absolute_url }}">{{ process }}</a>{% endwith %}
  </li>
  <li class="breadcrumb-item">
    <a href="{{ object.get_absolute_url }}">{{ object }}</a>
  </li>
{% endblock breadcrumbs %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <div class="alert alert-danger">
      {% blocktrans %}Are you sure you want to delete "{{ object }}"?{% endblocktrans %}
    </div>
    <div class="text-end">
      <div class="btn-group">
        <input class="btn btn-danger" type="submit" value='{% trans "Confirm" %}'>
        <a class="btn btn-outline-secondary"
           href="{{ object.get_absolute_url }}">{% trans "Cancel" %}</a>
      </div>
    </div>
  </form>
{% endblock content %}

processes/templates/processes/processversion/detail.html
{% extends "base.html" %}

{% load i18n %}

{% block options %}
  {% if processversion.can_be_updated and perms.processes.publish_processversion %}
    {% include "processes/includes/publish_modal.html" %}
  {% endif %}
  {% if processversion.can_be_updated and perms.processes.add_processactivity %}
    <a class="btn btn-sm btn-outline-secondary"
       href="{% url 'processactivity_create' processversion.pk %}">
      {% trans "Add process activity" %}
      <i class="fa fa-plus"></i>
    </a>
  {% endif %}
  {% if processversion.can_be_updated and perms.processes.change_processversion %}
    <a class="btn btn-sm btn-outline-secondary"
       href="{% url 'processversion_update' processversion.id %}">
      {% trans "Update process version" %}
      <i class="fa fa-edit"></i>
    </a>
  {% endif %}
  {% if processversion.can_be_updated and perms.processes.delete_processversion %}
    <a class="btn btn-sm btn-danger"
       href="{% url 'processversion_delete' processversion.id %}">
      {% trans "Delete process version" %}
      <i class="fa fa-times"></i>
    </a>
  {% endif %}
{% endblock options %}

{% block breadcrumbs %}
  <li class="breadcrumb-item">
    <a href="{% url 'process_list' %}">{% trans "processes"|capfirst %}</a>
  </li>
  <li class="breadcrumb-item">
    {% with process=processversion.process %}<a href="{{ process.get_absolute_url }}">{{ process }}</a>{% endwith %}
  </li>
{% endblock breadcrumbs %}

{% block content %}
  <table class="table table-striped table-hover table-sm">
    <tbody>
      <tr>
        <th>{% trans "process"|capfirst %}</th>
        {% with process=processversion.process %}
          <td>
            <a href="{{ process.get_absolute_url }}">{{ process }}</a>
          </td>
        {% endwith %}
      </tr>
      <tr>
        <th>{% trans "defined in"|capfirst %}</th>
        {% with defined_in=processversion.defined_in %}
          <td>
            <a href="{{ defined_in.get_absolute_url }}">{{ defined_in }}</a>
          </td>
        {% endwith %}
      </tr>
      <tr>
        <th>{% trans "published"|capfirst %}</th>
        <td>{{ processversion.is_published|yesno|capfirst }}</td>
      </tr>
      <tr>
        <th>{% trans "recurrency"|capfirst %}</th>
        <td>{{ processversion.get_recurrency_display|default:"-" }}</td>
      </tr>
      <tr>
        <th>{% trans "email to notifiy completion"|capfirst %}</th>
        <td>{{ processversion.email_to_notify_completion|default:"-" }}</td>
      </tr>
      <tr>
        <th>{% trans "created at"|capfirst %}</th>
        <td>{{ processversion.created_at }}</td>
      </tr>
      <tr>
        <th>{% trans "created by"|capfirst %}</th>
        <td>{{ processversion.created_by.get_label }}</td>
      </tr>
      <tr>
        <th>{% trans "updated at"|capfirst %}</th>
        <td>{{ processversion.updated_at }}</td>
      </tr>
      <tr>
        <th>{% trans "updated by"|capfirst %}</th>
        <td>{{ processversion.updated_by.get_label }}</td>
      </tr>
    </tbody>
  </table>
  <br>
  <h2>{% trans "controls"|capfirst %}</h2>
  {% include "documents/includes/control_table.html" with object_list=processversion.controls.all %}
  <br>
  <h2>{% trans "activities"|capfirst %}</h2>
  {% include "processes/includes/processactivity_table.html" with object_list=processversion.activities.all %}
{% endblock content %}

processes/templates/processes/processversion/update.html
{% extends "form.html" %}

{% load i18n %}

{% block breadcrumbs %}
  <li class="breadcrumb-item">
    <a href="{% url 'process_list' %}">{% trans "processes"|capfirst %}</a>
  </li>
  <li class="breadcrumb-item">
    {% with process=object.process %}<a href="{{ process.get_absolute_url }}">{{ process }}</a>{% endwith %}
  </li>
  <li class="breadcrumb-item">
    <a href="{{ object.get_absolute_url }}">{{ object }}</a>
  </li>
{% endblock breadcrumbs %}