project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

from base.views import debug as debug_views
from base.views import misc as misc_views

debug_patterns = [
    path("request/", debug_views.HttpRequestPrintView.as_view(), name="debug-request"),
]

urlpatterns = [
    path("admin/", include("loginas.urls")),
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("debug/", include(debug_patterns)),
    path("regions/", include("regions.urls")),
    path("status/", misc_views.StatusView.as_view(), name="status"),
    path("api/v1/", include("dummy_app.urls")),
    path("", misc_views.IndexView.as_view(), name="home"),
    path("", include("documents.urls")),
    path("", include("information_assets.urls")),
    path("risks/", include("risks.urls")),
    path("", include("processes.urls")),
    path("", include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    if not settings.TEST:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    if settings.ENABLE_DEBUG_TOOLBAR:
        # others libraries
        import debug_toolbar

        urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

elif settings.LOCAL_PROD_TESTING:
    # For simplicity, use the development server to serve static and media,
    # even with DEBUG=False.

    # "static(...)" is a no-op when DEBUG is False. So work around that guard:
    original_debug = settings.DEBUG
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    settings.DEBUG = original_debug


# custom error views
handler400 = "base.views.misc.bad_request_view"
handler403 = "base.views.misc.permission_denied_view"
handler404 = "base.views.misc.page_not_found_view"
handler500 = "base.views.misc.server_error_view"

risks/urls.py
from django.urls import path

from risks.views import risk as risk_views

urlpatterns = [
    path(
        "",
        risk_views.RiskListView.as_view(),
        name="risk_list",
    ),
    path(
        "create/",
        risk_views.RiskCreateView.as_view(),
        name="risk_create",
    ),
    path(
        "<int:pk>/",
        risk_views.RiskDetailView.as_view(),
        name="risk_detail",
    ),
    path(
        "<int:pk>/update/",
        risk_views.RiskUpdateView.as_view(),
        name="risk_update",
    ),
    path(
        "<int:pk>/delete/",
        risk_views.RiskDeleteView.as_view(),
        name="risk_delete",
    ),
]

users/urls.py
""" this document defines the users app urls """

from django.contrib.auth import views as auth_views
from django.urls import include
from django.urls import path

from users.views import groups as group_views
from users.views import users as user_views

group_urlpatterns = [
    path(
        "",
        group_views.GroupListView.as_view(),
        name="group_list",
    ),
    path(
        "create/",
        group_views.GroupCreateView.as_view(),
        name="group_create",
    ),
    path(
        "<int:pk>/",
        group_views.GroupDetailView.as_view(),
        name="group_detail",
    ),
    path(
        "<int:pk>/update/",
        group_views.GroupUpdateView.as_view(),
        name="group_update",
    ),
    path(
        "<int:pk>/delete/",
        group_views.GroupDeleteView.as_view(),
        name="group_delete",
    ),
]

user_urlpatterns = [
    path(
        "",
        user_views.UserListView.as_view(),
        name="user_list",
    ),
    path("create/", user_views.UserCreateView.as_view(), name="user_create"),
    path("<int:pk>/", user_views.UserDetailView.as_view(), name="user_detail"),
    path("<int:pk>/update/", user_views.UserUpdateView.as_view(), name="user_update"),
    path("<int:pk>/delete/", user_views.UserDeleteView.as_view(), name="user_delete"),
    path("login/", user_views.LoginView.as_view(), name="login"),
    path(
        "register/",
        user_views.UserRegisterView.as_view(),
        name="register",
    ),
    path(
        "password-change/",
        user_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password-change/done/",
        user_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "password-reset/",
        user_views.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "reset/<uidb64>/<token>/",
        user_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "verify/<uidb36>/<token>/",
        user_views.user_new_confirm,
        name="user_new_confirm",
    ),
    path(
        "reset/done/",
        user_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path(
        "password-reset/done/",
        user_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path("edit/", user_views.UserProfileEditView.as_view(), name="user_profile_edit"),
    path("profile/", user_views.UserProfileView.as_view(), name="user_profile"),
]

urlpatterns = [
    path("accounts/", include(user_urlpatterns)),
    path("groups/", include(group_urlpatterns)),
]

users/models.py
""" Models for the users application.

All apps should use the users.User model for all users
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sessions.models import Session
from django.contrib.sites.shortcuts import get_current_site
from django.db import models
from django.template import loader
from django.utils import timezone
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from django.utils.translation import gettext_noop

from base.models import BaseModel

# messaging
from messaging import email_manager
from parameters.models import Parameter

# managers
from users.managers import UserManager

# mark for translation the app name
gettext_noop("Users")

if TYPE_CHECKING:
    from processes.managers import ProcessInstanceQuerySet
    from processes.managers import ProcessQuerySet


class User(AbstractBaseUser, PermissionsMixin, BaseModel):
    """
    User model with admin-compliant permissions.

    Email and password are required. Other fields are optional.
    """

    # required fields
    email = models.EmailField(
        _("email address"),
        unique=True,
        db_index=True,
    )
    # optional fields
    first_name = models.CharField(
        _("first name"),
        max_length=30,
        blank=True,
    )
    last_name = models.CharField(
        _("last name"),
        max_length=30,
        blank=True,
    )
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as "
            "active. Unselect this instead of deleting accounts.",
        ),
    )
    # auto fields
    date_joined = models.DateTimeField(
        _("date joined"),
        default=timezone.now,
        help_text=_("The date this user was created in the database"),
    )
    # Use UserManager to get the create_user method, etc.
    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    # public methods
    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = f"{self.first_name} {self.last_name}"
        return full_name.strip()

    def get_short_name(self):
        "Returns the short name for the user."
        return self.first_name

    # overwritten methods
    def save(self, *args, **kwargs):
        """store all emails in lowercase"""
        self.email = self.email.lower()

        super().save(*args, **kwargs)

    def send_example_email(self):
        email_manager.send_example_email(self.email)

    def send_recover_password_email(self, request=None):
        """
        Sends an email with the required token so a user can recover
        his/her password

        """
        template = "password_reset"

        current_site = get_current_site(request)
        site_name = current_site.name
        domain = current_site.domain

        template_vars = {
            "email": self.email,
            "domain": domain,
            "site_name": site_name,
            "uid": urlsafe_base64_encode(force_bytes(self.pk)),
            "user": self,
            "token": default_token_generator.make_token(self),
            "protocol": Parameter.value_for("DEFAULT_URL_PROTOCOL"),
        }

        subject_template_name = "registration/password_reset_subject.txt"
        title = loader.render_to_string(subject_template_name, template_vars)

        email_manager.send_emails(
            emails=(self.email,),
            template_name=template,
            subject=title,
            context=template_vars,
        )

    def force_logout(self):
        """
        Deletes all the sessions of the User
        """
        # delete all the sessions that match the user
        for s in Session.objects.all():
            if int(s.get_decoded().get("_auth_user_id")) == self.id:
                s.delete()

    def get_label(self):
        return f"{self.get_full_name()} ({self.email})"

    def get_instantiable_processes(self) -> ProcessQuerySet:
        from processes.models.process import Process

        return Process.objects.instantiable_by_user(user=self)

    def get_participating_process_instances(self) -> ProcessInstanceQuerySet:
        from processes.models.process_instance import ProcessInstance

        return ProcessInstance.objects.user_is_participant(user=self)

users/views.py
""" The users app views"""


from django.contrib import messages
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import default_token_generator
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.http import base36_to_int
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic.edit import CreateView

# views
from base.views.generic import BaseListView
from parameters.models import Parameter

# forms
from users.forms import AuthenticationForm
from users.forms import CaptchaAuthenticationForm
from users.forms import UserCreationForm
from users.forms import UserForm
from users.models import User


class LoginView(auth_views.LoginView):
    """view that renders the login"""

    template_name = "registration/login.html"
    form_class = AuthenticationForm
    title = _("Login")

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect("home")
        return super().get(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.title

        return context

    def get_form_class(self):
        parameter = Parameter.value_for("ENABLE_LOGIN_RECAPTCHA")
        if parameter:
            return CaptchaAuthenticationForm
        return super().get_form_class()


class PasswordChangeView(auth_views.PasswordChangeView):
    """view that renders the password change form"""

    template_name = "registration/password_change_form.html"


class PasswordChangeDoneView(auth_views.PasswordChangeDoneView):
    template_name = "registration/password_change_done.html"


class PasswordResetView(auth_views.PasswordResetView):
    """view that handles the recover password process"""

    template_name = "registration/password_reset_form.html"
    email_template_name = "emails/password_reset.txt"


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    """view that handles the recover password process"""

    template_name = "registration/password_reset_confirm.html"


class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    """View that shows a success message to the user"""

    template_name = "registration/password_reset_done.html"


class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    """View that shows a success message to the user"""

    template_name = "registration/password_reset_complete.html"


class UserCreateView(CreateView):
    template_name = "users/create.html"
    form_class = UserCreationForm  # TODO Consider using captcha
    title = _("Registration")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.title

        return context

    def form_valid(self, form):
        form.save(verify_email_address=True, request=self.request)
        messages.add_message(
            self.request,
            messages.INFO,
            _(
                "An email has been sent to you. Please "
                "check it to verify your email.",
            ),
        )

        return redirect("home")


@login_required
def user_edit(request):
    if request.method == "POST":
        form = UserForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                _("Your data has been successfully saved."),
            )
            return redirect("home")
    else:
        form = UserForm(instance=request.user)

    context = {
        "cancel_url": reverse("user_profile"),
        "form": form,
    }

    return render(request, "users/edit.html", context)


@login_required
def user_profile(request):
    context = {"title": _("My profile")}

    return render(request, "users/detail.html", context)


# Doesn't need csrf_protect since no-one can guess the URL
@sensitive_post_parameters()
@never_cache
def user_new_confirm(  # noqa: PLR0913
    request,
    uidb36=None,
    token=None,
    token_generator=default_token_generator,
    current_app=None,
    extra_context=None,
):
    """
    View that checks the hash in a email confirmation link and activates
    the user.
    """
    if uidb36 is None or token is None:
        msg = "uidb36 and token are required"
        raise ValueError(msg)
    try:
        uid_int = base36_to_int(uidb36)
        user = User.objects.get(id=uid_int)
    except (ValueError, User.DoesNotExist):
        user = None

    if user is not None and token_generator.check_token(user, token):
        user.update(is_active=True)
        messages.add_message(
            request,
            messages.INFO,
            _("Your email address has been verified."),
        )
    else:
        messages.add_message(request, messages.ERROR, _("Invalid verification link"))

    return redirect("login")


class UserListView(BaseListView):
    model = User
    template_name = "users/list.html"
    ordering = ("first_name", "last_name")

    def get_queryset(self):
        queryset = super().get_queryset()

        # search users
        q = self.request.GET.get("q")
        if q:
            queryset = queryset.search(q)

        return queryset.prefetch_related("groups")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # we want to show a list of groups in each user, so we
        # iterate through each user, and create a string with the groups
        for obj in context["object_list"]:
            obj.group_names = " ".join([g.name for g in obj.groups.all()])

        return context

users/views/groups.py
from typing import Any

from base.views.generic.detail import BaseDetailView
from base.views.generic.edit import BaseCreateView
from base.views.generic.edit import BaseDeleteView
from base.views.generic.edit import BaseUpdateView
from base.views.generic.list import BaseListView
from users.forms import GroupForm
from users.models.group import Group


class GroupListView(BaseListView):
    model = Group
    ordering = ("name",)
    template_name = "groups/list.html"
    permission_required = "auth.view_group"


class GroupCreateView(BaseCreateView):
    model = Group
    form_class = GroupForm
    template_name = "groups/create.html"
    permission_required = "auth.add_group"

    def get_form_kwargs(self) -> dict[str, Any]:
        return {**super().get_form_kwargs(), "user": self.request.user}


class GroupDetailView(BaseDetailView):
    model = Group
    template_name = "groups/detail.html"
    permission_required = "auth.view_group"


class GroupUpdateView(BaseUpdateView):
    model = Group
    form_class = GroupForm
    template_name = "groups/update.html"
    permission_required = "auth.change_group"

    def get_form_kwargs(self) -> dict[str, Any]:
        return {**super().get_form_kwargs(), "user": self.request.user}


class GroupDeleteView(BaseDeleteView):
    model = Group
    template_name = "groups/delete.html"
    permission_required = "auth.delete_group"

users/templates/users/create.html
{% extends "form.html" %}

{% load i18n static %}

{% block breadcrumbs %}
  <li class="breadcrumb-item">
    <a href="{% url 'user_list' %}">{% trans "users"|capfirst %}</a>
  </li>
{% endblock breadcrumbs %}

users/templates/users/delete.html
{% extends "base.html" %}

{% load i18n %}

{% block breadcrumbs %}
  <li class="breadcrumb-item">
    <a href="{% url 'user_list' %}">{% trans "users"|capfirst %}</a>
  </li>
  <li class="breadcrumb-item">
    <a href="{% url 'user_detail' object.pk %}">{{ object }}</a>
  </li>
{% endblock breadcrumbs %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <div class="alert alert-danger">
      {% blocktrans %}Are you sure you want to delete "{{ object }}"?{% endblocktrans %}
    </div>
    <div class="text-end">
      <div class="btn-group">
        <input class="btn btn-danger" type="submit" value='{% trans "Confirm" %}'>
        <a class="btn btn-outline-secondary"
           href="{% url 'user_detail' object.pk %}">{% trans "Cancel" %}</a>
      </div>
    </div>
  </form>
{% endblock content %}

users/templates/users/detail.html
{% extends "base.html" %}

{% load i18n %}

{% block options %}
  {% if perms.users.change_user %}
    <a class="btn btn-sm btn-outline-secondary"
       href="{% url 'user_update' object.pk %}">
      {% trans "Update user" %}
      <i class="fa fa-edit"></i>
    </a>
  {% else %}
    <a class="btn btn-sm btn-outline-secondary"
       href="{% url 'user_profile_edit' %}">
      {% trans "Edit profile" %}
      <i class="fa fa-edit"></i>
    </a>
  {% endif %}
  {% if perms.users.delete_user %}
    <a class="btn btn-sm btn-danger"
       href="{% url 'user_delete' object.pk %}">
      {% trans "Delete user" %}
      <i class="fa fa-times"></i>
    </a>
  {% endif %}
{% endblock options %}

{% block breadcrumbs %}
  {% if perms.users.view_user %}
    <li class="breadcrumb-item">
      <a href="{% url 'user_list' %}">{% trans "users"|capfirst %}</a>
    </li>
  {% endif %}
{% endblock breadcrumbs %}

{% block content %}
  <div class="detail">
    <div class="row">
      <div class="col-md-7">
        <table class="table table-striped table-hover table-bordered table-sm">
          <tr>
            <th>{% trans "first name"|capfirst %}</th>
            <td>{{ object.first_name }}</td>
          </tr>
          <tr>
            <th>{% trans "last name"|capfirst %}</th>
            <td>{{ object.last_name }}</td>
          </tr>
          <tr>
            <th>{% trans "email"|capfirst %}</th>
            <td>{{ object.email }}</td>
          </tr>
          <tr>
            <th>{% trans "is active"|capfirst %}</th>
            <td>{{ object.is_active|yesno|capfirst }}</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
  {% if perms.auth.view_group %}
    <br>
    <h2>{% trans "assigned groups"|capfirst %}</h2>
    {% include "groups/includes/group_table.html" with object_list=object.groups.all %}
  {% endif %}
{% endblock content %}

users/templates/users/list.html
{% extends "base.html" %}

{% load i18n %}

{% block options %}
  {% if perms.users.add_user %}
    <a class="btn btn-sm btn-outline-secondary"
       href="{% url 'user_create' %}">
      {% trans "Add user" %}
      <i class="fa fa-plus"></i>
    </a>
  {% endif %}
{% endblock options %}

{% block content %}
  <div class="row">
    <div class="offset-sm-8 col-sm-4">
      <form>
        <div class="input-group mb-3">
          <input class="form-control"
                 name="q"
                 placeholder='{% trans "Search by name or email" %}'
                 type="text"
                 value="{{ q|default:'' }}" />
          <button class="btn btn-outline-secondary" type="submit">
            <i class="fa fa-search"></i>
          </button>
        </div>
        {% for order in ordering %}<input type="hidden"  name="o"  value="{{ order }}">{% endfor %}
      </form>
    </div>
  </div>

  <table class="table table-striped table-sm">
    <thead>
      <tr>
        {% include "includes/list_th.html" with order_by="first_name" verbose_name="name" %}
        {% include "includes/list_th.html" with order_by="email" verbose_name="email" %}
        {% include "includes/list_th.html" with order_by="is_active" verbose_name="is active" %}
        {% include "includes/list_th.html" with order_by="groups" verbose_name="groups" %}
        {% if perms.users.change_user or perms.users.delete_user %}<th></th>{% endif %}
      </tr>
    </thead>

    <tbody>
      {% for iter_user in user_list %}
        <tr>
          <td>
            <a href="{% url 'user_detail' iter_user.pk %}">{{ iter_user.get_full_name }}</a>
          </td>
          <td>{{ iter_user.email }}</td>
          <td>{{ iter_user.is_active|yesno|capfirst }}</td>
          <td>{{ iter_user.groups.all|join:", " }}</td>
          {% if perms.users.change_user or perms.users.delete_user %}
            <td class="text-end">
              {% if perms.users.change_user %}
                <a class="btn btn-sm btn-outline-secondary"
                   href="{% url 'user_update' iter_user.pk %}">
                  {% trans "Update user" %}
                  <i class="fa fa-edit"></i>
                </a>
              {% endif %}
              {% if perms.documents.delete_document %}
                <a class="btn btn-sm btn-danger"
                   href="{% url 'user_delete' iter_user.pk %}">
                  {% trans "Delete user" %}
                  <i class="fa fa-times"></i>
                </a>
              {% endif %}
            </td>
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% include "includes/pagination.html" with objects=page_obj %}
{% endblock content %}

users/templates/users/login.html
{% extends "form.html" %}

{% load i18n static %}

{% block legacy_javascripts %}
  <script src="{% static 'js/login.js' %}"></script>
{% endblock legacy_javascripts %}

{% block content %}
  {% if google_oauth_enabled %}
    <form action='{% url "social:begin" "google-oauth2" %}' method="post">
      <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />
      <button type="submit" class="btn btn-danger">
        <i class="fa fa-google"></i>
        {% trans "Log in with Google" %}
      </button>
    </form>
  {% endif %}
  {% if django_auth_enabled %}
    <form id="login-form"
          class="mt-4"
          action=""
          method="post"
          data-username-field-id="id_{{ form.email_field.name }}">
      {% csrf_token %}

      {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}<div class="alert alert-danger">{{ error }}</div>{% endfor %}
      {% endif %}
      {% if "captcha" in form.errors %}<div class="alert alert-danger">{{ form.captcha.errors }}</div>{% endif %}

      {% for field in form.hidden_fields %}{{ field }}{% endfor %}
      <input id="id_next" type="hidden" name="next" value="{{ next }}" />

      {% for field in form.visible_fields %}
        <div class="row">
          <div class="mb-3 col-6">
            <label for="id_{{ field.name }}">{{ field.label }}</label>
            {{ field }}
            {% if field.errors %}<div class="invalid-feedback">{{ field.errors|striptags }}</div>{% endif %}

            {% if field.help_text %}<small class="form-text" id="{{ field.name }}Help">{{ field.help_text }}</small>{% endif %}
          </div>
        </div>
      {% endfor %}

      <div class="row">
        <div class="mb-3 col-sm-6 text-end">
          <button class="btn btn-primary" type="submit" value="">{% trans "Log in" %}</button>
        </div>
      </div>

      <div>
        <a href="{% url 'password_reset' %}">{% trans "Forgotten your password?" %}</a>
      </div>
      {% if user_registration_enabled %}
        <div>
          <a href="{% url 'register' %}">{% trans "New? Register here." %}</a>
        </div>
      {% endif %}
    </form>
  {% endif %}
{% endblock content %}

users/templates/users/password_change_done.html
{% extends "base.html" %}
{% load i18n %}

{% block breadcrumbs %}
  <li class="breadcrumb-item">{% trans "Password change" %}</li>
{% endblock breadcrumbs %}

{% block content %}
  <div class="alert alert-info">{% trans "Your password was changed." %}</div>
{% endblock content %}

users/templates/users/password_change_form.html
{% extends "base.html" %}

{% load i18n static %}

{% block legacy_javascripts %}
  <script type="text/javascript">document.getElementById("id_old_password").focus();</script>
{% endblock legacy_javascripts %}

{% block content %}
  {% if form.errors %}
    <div class="alert alert-danger">
      {% blocktrans count counter=form.errors.items|length %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}
    </div>
  {% endif %}

  <div class="alert alert-info">
    {% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}
  </div>

  <form action=""  method='post'>
    {% csrf_token %}
    <fieldset>
      <div class="row">
        <div class="col-sm-6">
          <div class="mb-3">
            <label class="col-form-label" required for="id_old_password">{% trans "Old password" %}:</label>
            <input id="id_old_password"
                   class="form-control"
                   name='old_password'
                   type='password'
                   placeholder='{% trans "Old password" %}'>
            <span class="invalid-feedback d-block"
                  for="id_{{ form.old_password.name }}">{{ form.old_password.errors|striptags }}</span>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-6">
          <div class="mb-3">
            <label class="col-form-label" required for="id_new_password1">{% trans "New password" %}:</label>
            <input id="id_new_password1"
                   class="form-control"
                   name="new_password1"
                   type="password"
                   placeholder='{% trans "New password" %}'>
            <span class="invalid-feedback d-block">{{ form.new_password1.errors|striptags }}</span>
          </div>
        </div>
        <div class="col-sm-6">
          <small class="form-text" id="{{ form.new_password.name }}_help">{{ form.new_password1.help_text|safe }}</small>
        </div>

        <div class="row">
          <div class="col-sm-6">
            <div class="mb-3">
              <label class="col-form-label" required for="id_new_password2">{% trans "Password (again)" %}:</label>
              <input id="id_new_password2"
                     class="form-control"
                     name="new_password2"
                     type="password"
                     placeholder='{% trans "Password (again)" %}'>
              <span class="invalid-feedback d-block">{{ form.new_password2.errors|striptags }}</span>
            </div>
          </div>
          <div class="col-sm-6">{{ form.new_password2.help_text|safe }}</div>
        </div>

        <div class="row">
          <div class="col-sm-6">
            <div class="mb-3">
              <div class="text-end">
                <input class="btn btn-primary"
                       type="submit"
                       value='{% trans "Change my password" %}'>
              </div>
            </div>
          </div>
        </div>
      </div>
    </fieldset>
  </form>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
  <div class="alert alert-info">
    {% trans "Your password has been set.  You may go ahead and log in now." %}
    <a class="btn btn-primary" href="{{ login_url }}">{% trans "Log in" %}</a>
  </div>
{% endblock content %}

users/templates/users/password_reset_form.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
  <div class="alert alert-info">
    {% trans "Forgotten your password? Enter your e-mail address below, and we'll e-mail instructions for setting a new one." %}
  </div>

  <form action=""  method="post">
    {% csrf_token %}
    <div class="row">
      <div class="col-sm-6">
        <div class="mb-3">
          <label class="col-form-label" for="id_email">{% trans "E-mail address" %}:</label>
          <input id="id_email"
                 class="form-control"
                 maxlength="254"
                 name="email"
                 type="email"
                 value="{% if form.email.value %}{{ form.email.value }}{% endif %}">
          <span class="invalid-feedback d-block" for="id_{{ form.email.name }}">{{ form.old_password.errors|striptags }}</span>
        </div>
      </div>
      <div class="col-sm-6">
        <span class="invalid-feedback d-block">{{ form.email.errors }}</span>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <div class="mb-3 text-end">
          <input class="btn btn-primary"
                 type="submit"
                 value='{% trans "Reset my password" %}'>
        </div>
      </div>
    </div>
  </form>
{% endblock content %}

users/templates/users/update.html
{% extends "form.html" %}

{% load i18n %}

{% block breadcrumbs %}
  {% if perms.users.view_user %}
    <li class="breadcrumb-item">
      <a href="{% url 'user_list' %}">{{ opts.verbose_name_plural|capfirst }}</a>
    </li>
  {% endif %}
  {% if perms.users.view_user %}
    <li class="breadcrumb-item">
      <a href="{% url 'user_detail' object.pk %}">{{ object }}</a>
    </li>
  {% else %}
    <li class="breadcrumb-item">
      <a href="{% url 'user_profile' %}">{% trans "My profile" %}</a>
    </li>
  {% endif %}
{% endblock breadcrumbs %}