processes/urls.py
from django.urls import include
from django.urls import path

from processes.views import process as process_views
from processes.views import process_activity as processactivity_views
from processes.views import process_activity_instance as processactivityinstance_views
from processes.views import process_instance as processinstance_views
from processes.views import process_version as processversion_views

process_urlpatterns = [
    path(
        "",
        process_views.ProcessListView.as_view(),
        name="process_list",
    ),
    path(
        "create/",
        process_views.ProcessCreateView.as_view(),
        name="process_create",
    ),
    path(
        "<int:pk>/",
        process_views.ProcessDetailView.as_view(),
        name="process_detail",
    ),
    path(
        "<int:pk>/update/",
        process_views.ProcessUpdateView.as_view(),
        name="process_update",
    ),
    path(
        "<int:pk>/delete/",
        process_views.ProcessDeleteView.as_view(),
        name="process_delete",
    ),
]

processversion_urlpatterns = [
    path(
        "<int:parent_pk>/versions/create/",
        processversion_views.ProcessVersionCreateView.as_view(),
        name="processversion_create",
    ),
    path(
        "versions/<int:pk>/",
        processversion_views.ProcessVersionDetailView.as_view(),
        name="processversion_detail",
    ),
    path(
        "versions/<int:pk>/update/",
        processversion_views.ProcessVersionUpdateView.as_view(),
        name="processversion_update",
    ),
    path(
        "versions/<int:pk>/delete/",
        processversion_views.ProcessVersionDeleteView.as_view(),
        name="processversion_delete",
    ),
    path(
        "versions/<int:pk>/publish/",
        processversion_views.ProcessVersionPublishView.as_view(),
        name="processversion_publish",
    ),
    path(
        "versions/<int:parent_pk>/activities/create/",
        processactivity_views.ProcessActivityCreateView.as_view(),
        name="processactivity_create",
    ),
]

processinstance_urlpatterns = [
    path(
        "",
        processinstance_views.ProcessInstanceListView.as_view(),
        name="processinstance_list",
    ),
    path(
        "create/",
        processinstance_views.ProcessInstanceCreateView.as_view(),
        name="processinstance_create",
    ),
    path(
        "<int:pk>/",
        processinstance_views.ProcessInstanceDetailView.as_view(),
        name="processinstance_detail",
    ),
    path(
        "<int:pk>/delete/",
        processinstance_views.ProcessInstanceDeleteView.as_view(),
        name="processinstance_delete",
    ),
]

processactivity_urlpatterns = [
    path(
        "<int:pk>/",
        processactivity_views.ProcessActivityDetailView.as_view(),
        name="processactivity_detail",
    ),
    path(
        "<int:pk>/update/",
        processactivity_views.ProcessActivityUpdateView.as_view(),
        name="processactivity_update",
    ),
    path(
        "<int:pk>/delete/",
        processactivity_views.ProcessActivityDeleteView.as_view(),
        name="processactivity_delete",
    ),
]

processactivityinstance_urlpatterns = [
    path(
        "<int:pk>/",
        processactivityinstance_views.ProcessActivityInstanceDetailView.as_view(),
        name="processactivityinstance_detail",
    ),
    path(
        "<int:pk>/complete/",
        processactivityinstance_views.ProcessActivityInstanceCompleteView.as_view(),
        name="processactivityinstance_complete",
    ),
]

urlpatterns = [
    path("processes/", include(process_urlpatterns)),
    path("processes/", include(processversion_urlpatterns)),
    path("process-instances/", include(processinstance_urlpatterns)),
    path("activities/", include(processactivity_urlpatterns)),
    path("activity-instances/", include(processactivityinstance_urlpatterns)),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

from base.views import debug as debug_views
from base.views import misc as misc_views

debug_patterns = [
    path("request/", debug_views.HttpRequestPrintView.as_view(), name="debug-request"),
]

urlpatterns = [
    path("admin/", include("loginas.urls")),
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("debug/", include(debug_patterns)),
    path("regions/", include("regions.urls")),
    path("status/", misc_views.StatusView.as_view(), name="status"),
    path("api/v1/", include("dummy_app.urls")),
    path("", misc_views.IndexView.as_view(), name="home"),
    path("", include("documents.urls")),
    path("", include("information_assets.urls")),
    path("risks/", include("risks.urls")),
    path("", include("processes.urls")),
    path("", include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    if not settings.TEST:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    if settings.ENABLE_DEBUG_TOOLBAR:
        # others libraries
        import debug_toolbar

        urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

elif settings.LOCAL_PROD_TESTING:
    # For simplicity, use the development server to serve static and media,
    # even with DEBUG=False.

    # "static(...)" is a no-op when DEBUG is False. So work around that guard:
    original_debug = settings.DEBUG
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    settings.DEBUG = original_debug


# custom error views
handler400 = "base.views.misc.bad_request_view"
handler403 = "base.views.misc.permission_denied_view"
handler404 = "base.views.misc.page_not_found_view"
handler500 = "base.views.misc.server_error_view"

risks/urls.py
from django.urls import path

from risks.views import risk as risk_views

urlpatterns = [
    path(
        "",
        risk_views.RiskListView.as_view(),
        name="risk_list",
    ),
    path(
        "create/",
        risk_views.RiskCreateView.as_view(),
        name="risk_create",
    ),
    path(
        "<int:pk>/",
        risk_views.RiskDetailView.as_view(),
        name="risk_detail",
    ),
    path(
        "<int:pk>/update/",
        risk_views.RiskUpdateView.as_view(),
        name="risk_update",
    ),
    path(
        "<int:pk>/delete/",
        risk_views.RiskDeleteView.as_view(),
        name="risk_delete",
    ),
]

processes/models/process_activity.py
from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from base.models.base_model import BaseModel
from base.models.increment_field_mixin import IncrementFieldModelBase
from users.models.group import Group

if TYPE_CHECKING:
    from processes.models.process_activity_instance import ProcessActivityInstance
    from processes.models.process_instance import ProcessInstance
    from users.models.user import User


class ProcessActivity(IncrementFieldModelBase, BaseModel):
    process_version = models.ForeignKey(
        verbose_name=_("process version"),
        to="ProcessVersion",
        on_delete=models.PROTECT,
        related_name="activities",
    )
    order = models.PositiveIntegerField(verbose_name=_("order"))
    title = models.CharField(
        verbose_name=_("title"),
        max_length=255,
    )
    description = models.TextField(verbose_name=_("description"))
    assignee_groups = models.ManyToManyField(
        verbose_name=_("assignee groups"),
        to=Group,
        related_name="activities",
    )
    deliverables = models.TextField(
        verbose_name=_("deliverables"),
        blank=True,
    )
    email_to_notify = models.EmailField(
        verbose_name=_("email to notify"),
        blank=True,
    )

    class Meta:
        verbose_name = _("process activity")
        verbose_name_plural = _("process activities")
        ordering = ("process_version", "order")

    @property
    def can_be_updated(self) -> bool:
        return self.process_version.can_be_updated

    def __str__(self) -> str:
        return self.title

    def _get_increment_queryset(self) -> models.QuerySet[ProcessActivity]:
        return self.process_version.activities.all()

    def _get_field_to_increment(self) -> str:
        return "order"

    def create_instance(
        self, process_instance: ProcessInstance, assignee: User | None = None
    ) -> ProcessActivityInstance:
        from processes.models.process_activity_instance import ProcessActivityInstance

        if assignee is None:
            assignee = process_instance.created_by
        return ProcessActivityInstance.objects.create(
            process_instance=process_instance,
            activity=self,
            assignee=assignee,
        )

    def get_next_activity(self) -> ProcessActivity | None:
        qs = self.process_version.activities.filter(order__gt=self.order)
        if qs.exists():
            return qs.earliest("order")
        return None

    def get_absolute_url(self) -> str:
        return reverse("processactivity_detail", args=(self.pk,))

processes/models/process_activity_instance.py
from __future__ import annotations

from typing import TYPE_CHECKING

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from base.models.base_model import BaseModel
from base.utils import build_absolute_url_wo_req
from documents.models.evidence import Evidence
from messaging.email_manager import send_emails
from processes.managers import ProcessActivityInstanceQuerySet
from processes.models.process_activity import ProcessActivity
from processes.models.process_instance import ProcessInstance
from processes.tasks import send_activity_instance_completion_notification
from processes.tasks import send_activity_instance_notification

if TYPE_CHECKING:
    from processes.forms import ProcessActivityInstanceCompleteForm


class ProcessActivityInstance(BaseModel):
    process_instance = models.ForeignKey(
        verbose_name=_("process instance"),
        to=ProcessInstance,
        on_delete=models.PROTECT,
        related_name="activity_instances",
    )
    activity = models.ForeignKey(
        verbose_name=_("activity"),
        to=ProcessActivity,
        on_delete=models.PROTECT,
        related_name="activity_instances",
    )
    assignee = models.ForeignKey(
        verbose_name=_("assignee"),
        to=settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="activity_instances",
    )
    is_completed = models.BooleanField(
        verbose_name=_("is completed"),
        default=False,
    )
    completed_at = models.DateTimeField(
        verbose_name=_("completed at"),
        null=True,
        blank=True,
    )
    evidence = models.OneToOneField(
        verbose_name=_("evidence"),
        to=Evidence,
        on_delete=models.PROTECT,
        related_name="process_activity_instance",
        null=True,
    )

    objects = ProcessActivityInstanceQuerySet.as_manager()

    class Meta:
        verbose_name = _("process activity instance")
        verbose_name_plural = _("process activity instances")
        ordering = ("-pk",)

    def __str__(self) -> str:
        return str(self.activity)

    def send_email_notification(self) -> None:
        context = {
            "process_instance": self.process_instance,
            "process_instance_url": build_absolute_url_wo_req(
                self.process_instance.get_absolute_url()
            ),
            "previous_activity_instance": self.get_previous_activity_instance(),
            "activity_instance": self,
            "activity_instance_url": build_absolute_url_wo_req(self.get_absolute_url()),
        }
        send_emails(
            emails=(self.get_email_to_notify(),),
            template_name="processactivityinstance_notification",
            subject=str(self),
            context=context,
        )

    def get_email_to_notify(self) -> str:
        return (
            self.activity.email_to_notify
            if self.activity.email_to_notify
            else self.assignee.email
        )

    def send_email_completion_notification(self, email_to_notify) -> None:
        context = {
            "process_instance": self.process_instance,
            "process_instance_url": build_absolute_url_wo_req(
                self.process_instance.get_absolute_url()
            ),
            "activity_instance": self,
            "activity_instance_url": build_absolute_url_wo_req(self.get_absolute_url()),
        }
        send_emails(
            emails=(email_to_notify,),
            template_name="processactivityinstance_completion_notification",
            subject=f"{self.process_instance.process_version.process.name} finalizado",
            context=context,
        )

    def get_next_activity(self) -> ProcessActivity | None:
        return self.activity.get_next_activity()

    def get_previous_activity_instance(self) -> ProcessActivityInstance | None:
        qs = self.process_instance.activity_instances.filter(
            activity__order__lt=self.activity.order
        )
        if qs.exists():
            return qs.latest("activity__order")
        return None

    def get_absolute_url(self) -> str:
        return reverse("processactivityinstance_detail", args=(self.pk,))

    def mark_as_completed(self, form: ProcessActivityInstanceCompleteForm) -> None:
        evidence = Evidence.create_from_form(form)
        next_activity_instance = self.create_next_activity_instance_if_exists(form)
        self.update(evidence=evidence, is_completed=True, completed_at=timezone.now())
        self.notify_if_required(form, next_activity_instance)
        self.process_instance.check_if_completed()

    def create_next_activity_instance_if_exists(
        self, form: ProcessActivityInstanceCompleteForm
    ) -> ProcessActivityInstance | None:
        next_activity = self.get_next_activity()
        if next_activity is None:
            return None
        return next_activity.create_instance(
            process_instance=self.process_instance,
            assignee=form.cleaned_data["next_activity_assignee"],
        )

    def notify_if_required(
        self,
        form: ProcessActivityInstanceCompleteForm,
        next_activity_instance: ProcessActivityInstance,
    ) -> None:
        if next_activity_instance is not None:
            send_activity_instance_notification.delay(next_activity_instance.pk)
        elif email_to_notify := form.cleaned_data["email_to_notify"]:
            send_activity_instance_completion_notification.delay(
                self.pk, email_to_notify
            )

processes/models/process_instance.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from base.models.base_model import BaseModel
from processes.managers import ProcessInstanceQuerySet
from processes.models.process_version import ProcessVersion


class ProcessInstance(BaseModel):
    process_version = models.ForeignKey(
        verbose_name=_("process version"),
        to=ProcessVersion,
        on_delete=models.PROTECT,
        related_name="instances",
    )
    comment = models.TextField(verbose_name=_("comment"), blank=True)
    is_completed = models.BooleanField(verbose_name=_("is completed"), default=False)
    completed_at = models.DateTimeField(
        verbose_name=_("completed at"), blank=True, null=True
    )

    objects = ProcessInstanceQuerySet.as_manager()

    class Meta:
        verbose_name = _("process instance")
        verbose_name_plural = _("process instances")

    def __str__(self) -> str:
        return f"{self.process_version} Instance"

    def save(self, *args, **kwargs) -> None:
        adding = self._state.adding
        super().save(*args, **kwargs)
        if adding:
            self.process_version.create_first_activity_instance(self)

    def get_absolute_url(self) -> str:
        return reverse("processinstance_detail", args=(self.pk,))

    def check_if_completed(self) -> None:
        if self.activity_instances.filter(is_completed=False).count() == 0:
            self.update(is_completed=True, completed_at=timezone.now())

processes/views/process.py
from base.views.generic.detail import BaseDetailView
from base.views.generic.edit import BaseCreateView
from base.views.generic.edit import BaseDeleteView
from base.views.generic.edit import BaseUpdateView
from base.views.generic.list import BaseListView
from processes.forms import ProcessForm
from processes.models.process import Process


class ProcessListView(BaseListView):
    model = Process
    template_name = "processes/process/list.html"
    permission_required = "processes.view_process"


class ProcessCreateView(BaseCreateView):
    model = Process
    form_class = ProcessForm
    template_name = "processes/process/create.html"
    permission_required = "processes.add_process"


class ProcessDetailView(BaseDetailView):
    model = Process
    template_name = "processes/process/detail.html"
    permission_required = "processes.view_process"


class ProcessUpdateView(BaseUpdateView):
    model = Process
    form_class = ProcessForm
    template_name = "processes/process/update.html"
    permission_required = "processes.change_process"


class ProcessDeleteView(BaseDeleteView):
    model = Process
    template_name = "processes/process/delete.html"
    permission_required = "processes.delete_process"

processes/templates/processes/includes/process_table.html
{% load i18n %}

<table class="table table-striped table-hover table-sm">
  <thead>
    <tr>
      <th>{% trans "name"|capfirst %}</th>
      <th>{% trans "last published version"|capfirst %}</th>
      <th>{% trans "last version"|capfirst %}</th>
      <th>{% trans "updated at"|capfirst %}</th>
      <th>{% trans "updated by"|capfirst %}</th>
      {% if perms.processes.change_process or perms.processes.delete_process or perms.processes.add_processinstance or perms.processes.add_processversion %}
        <th></th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for process in object_list %}
      <tr>
        <td>
          <a href="{{ process.get_absolute_url }}">{{ process }}</a>
        </td>
        <td>
          {% with last_published_version=process.last_published_version %}
            {% if last_published_version is not None %}
              <a href="{{ last_published_version.get_absolute_url }}">{{ last_published_version }}</a>
            {% else %}
              -
            {% endif %}
          {% endwith %}
        </td>
        <td>
          {% with last_version=process.last_version %}
            {% if last_version is not None %}
              <a href="{{ last_version.get_absolute_url }}">{{ last_version }}</a>
            {% else %}
              -
            {% endif %}
          {% endwith %}
        </td>
        <td>{{ process.latest_update }}</td>
        <td>{{ process.latest_updator }}</td>
        {% if perms.processes.change_process or perms.processes.delete_process or perms.processes.add_processinstance or perms.processes.add_processversion %}
          <td class="text-end">
            {% if perms.processes.add_processinstance and process in user.get_instantiable_processes %}
              <a class="btn btn-sm btn-outline-secondary"
                 href="{% url 'processinstance_create' %}?process_pk={{ process.pk }}">
                {% trans "Start process" %}
                <i class="fa fa-plus"></i>
              </a>
            {% endif %}
            {% if process.can_add_new_versions and perms.processes.add_processversion %}
              <a class="btn btn-sm btn-outline-secondary"
                 href="{% url 'processversion_create' process.pk %}">
                {% trans "Add process version" %}
                <i class="fa fa-plus"></i>
              </a>
            {% endif %}
            {% if perms.processes.change_process %}
              <a class="btn btn-sm btn-outline-secondary"
                 href="{% url 'process_update' process.id %}">
                {% trans "Update process" %}
                <i class="fa fa-edit"></i>
              </a>
            {% endif %}
            {% if perms.processes.delete_process %}
              <a class="btn btn-sm btn-danger"
                 href="{% url 'process_delete' process.id %}">
                {% trans "Delete process" %}
                <i class="fa fa-times"></i>
              </a>
            {% endif %}
          </td>
        {% endif %}
      </tr>
    {% endfor %}
  </tbody>
</table>

processes/templates/processes/includes/processactivity_table.html
{% load i18n %}

<table class="table table-striped table-hover table-sm">
  <thead>
    <tr>
      <th>{% trans "title"|capfirst %}</th>
      <th>{% trans "description"|capfirst %}</th>
      <th>{% trans "assignee groups"|capfirst %}</th>
      <th>{% trans "updated at"|capfirst %}</th>
      <th>{% trans "updated by"|capfirst %}</th>
      {% if processversion.can_be_updated %}
        {% if perms.processes.change_processactivity or perms.processes.delete_processactivity %}<th></th>{% endif %}
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for process_activity in object_list %}
      <tr>
        <td>
          <a href="{{ process_activity.get_absolute_url }}">{{ process_activity }}</a>
        </td>
        <td>{{ process_activity.description|linebreaks }}</td>
        <td>{{ process_activity.assignee_groups.all|join:", " }}</td>
        <td>{{ process_activity.updated_at }}</td>
        <td>{{ process_activity.updated_by.get_label }}</td>
        {% if processversion.can_be_updated %}
          {% if perms.processes.change_processactivity or perms.processes.delete_processactivity %}
            <td class="text-end">
              {% if perms.processes.change_processactivity %}
                <a class="btn btn-sm btn-outline-secondary"
                   href="{% url 'processactivity_update' process_activity.id %}">
                  {% trans "Update process activity" %}
                  <i class="fa fa-edit"></i>
                </a>
              {% endif %}
              {% if perms.processes.delete_processactivity %}
                <a class="btn btn-sm btn-danger"
                   href="{% url 'processactivity_delete' process_activity.id %}">
                  {% trans "Delete process activity" %}
                  <i class="fa fa-times"></i>
                </a>
              {% endif %}
            </td>
          {% endif %}
        {% endif %}
      </tr>
    {% endfor %}
  </tbody>
</table>

processes/templates/processes/includes/processactivityinstance_table.html
{% load i18n %}

<table class="table table-striped table-hover table-sm">
  <thead>
    <tr>
      <th>{% trans "title"|capfirst %}</th>
      <th>{% trans "description"|capfirst %}</th>
      <th>{% trans "assignee"|capfirst %}</th>
      <th>{% trans "completed"|capfirst %}</th>
      <th>{% trans "completed at"|capfirst %}</th>
      {% if perms.processes.change_processactivityinstance and not process_activity_instance.process_instance.is_completed %}
        <th></th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for process_activity_instance in object_list %}
      <tr>
        <td>
          <a href="{{ process_activity_instance.get_absolute_url }}">{{ process_activity_instance }}</a>
        </td>
        <td>{{ process_activity_instance.activity.description|linebreaks }}</td>
        <td>{{ process_activity_instance.assignee.get_label }}</td>
        <td>{{ process_activity_instance.is_completed|yesno|capfirst }}</td>
        <td>{{ process_activity_instance.completed_at|default_if_none:"-" }}</td>
        {% if perms.processes.change_processactivityinstance and not process_activity_instance.process_instance.is_completed %}
          <td class="text-end">
            {% if perms.processes.change_processactivityinstance and process_activity_instance.assignee == view.request.user and not process_activity_instance.is_completed %}
              <a class="btn btn-sm btn-success"
                 href="{% url 'processactivityinstance_complete' process_activity_instance.pk %}">
                {% trans "Complete activity" %}
                <i class="fa fa-check"></i>
              </a>
            {% endif %}
          </td>
        {% endif %}
      </tr>
    {% endfor %}
  </tbody>
</table>

processes/templates/processes/includes/processinstance_table.html
{% load i18n %}

<table class="table table-striped table-hover table-sm">
  <thead>
    <tr>
      <th>{% trans "name"|capfirst %}</th>
      <th>{% trans "comment"|capfirst %}</th>
      <th>{% trans "updated at"|capfirst %}</th>
      <th>{% trans "updated by"|capfirst %}</th>
      <th>{% trans "completed"|capfirst %}</th>
      <th>{% trans "completed at"|capfirst %}</th>
      {% if perms.processes.delete_processinstance %}<th></th>{% endif %}
    </tr>
  </thead>
  <tbody>
    {% for process_instance in object_list %}
      <tr>
        <td>
          <a href="{{ process_instance.get_absolute_url }}">{{ process_instance }}</a>
        </td>
        {% with comment_label=process_instance.process_version.comment_label %}
          <td>
            {% if comment_label %}{{ comment_label }}:{% endif %}
            {{ process_instance.comment|default:"-"|linebreaks }}
          </td>
        {% endwith %}
        <td>{{ process_instance.created_at }}</td>
        <td>{{ process_instance.created_by.get_label }}</td>
        <td>{{ process_instance.is_completed|yesno|capfirst }}</td>
        <td>{{ process_instance.completed_at|default_if_none:"-" }}</td>
        {% if perms.processes.delete_processinstance %}
          <td class="text-end">
            {% if perms.processes.delete_processinstance and not process_instance.is_completed %}
              <a class="btn btn-sm btn-danger"
                 href="{% url 'processinstance_delete' process_instance.id %}">
                {% trans "Delete process instance" %}
                <i class="fa fa-times"></i>
              </a>
            {% endif %}
          </td>
        {% endif %}
      </tr>
    {% endfor %}
  </tbody>
</table>

processes/templates/processes/includes/processversion_table.html
{% load i18n %}

<table class="table table-striped table-hover table-sm">
  <thead>
    <tr>
      <th>{% trans "version"|capfirst %}</th>
      <th>{% trans "published"|capfirst %}</th>
      <th>{% trans "defined in"|capfirst %}</th>
      <th>{% trans "updated at"|capfirst %}</th>
      <th>{% trans "updated by"|capfirst %}</th>
      {% if not process.can_add_new_versions %}
        {% if perms.processes.change_processversion or perms.processes.delete_processversion or perms.processes.publish_processversion %}
          <th></th>
        {% endif %}
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for processversion in object_list %}
      <tr>
        <td>
          <a href="{{ processversion.get_absolute_url }}">V{{ processversion.version }}</a>
        </td>
        <td>{{ processversion.is_published|yesno|capfirst }}</td>
        <td>
          {% with defined_in=processversion.defined_in %}
            <a href="{{ defined_in.get_absolute_url }}">{{ defined_in }}</a>
          {% endwith %}
        </td>
        <td>{{ processversion.updated_at }}</td>
        <td>{{ processversion.updated_by.get_label }}</td>
        {% if not process.can_add_new_versions %}
          {% if processversion.can_be_updated %}

            {% if perms.processes.change_processversion or perms.processes.delete_processversion %}
              <td class="text-end">
                {% if perms.processes.publish_processversion %}
                  {% include "processes/includes/publish_modal.html" with processversion=processversion %}
                {% endif %}
                {% if perms.processes.change_processversion %}
                  <a class="btn btn-sm btn-outline-secondary"
                     href="{% url 'processversion_update' processversion.id %}">
                    {% trans "Update process version" %}
                    <i class="fa fa-edit"></i>
                  </a>
                {% endif %}
                {% if perms.processes.delete_processversion %}
                  <a class="btn btn-sm btn-danger"
                     href="{% url 'processversion_delete' processversion.id %}">
                    {% trans "Delete process version" %}
                    <i class="fa fa-times"></i>
                  </a>
                {% endif %}
              </td>
            {% endif %}
          {% else %}
            <td></td>
          {% endif %}
        {% endif %}
      </tr>
    {% endfor %}
  </tbody>
</table>

processes/templates/processes/includes/publish_modal.html
{% load i18n %}

<button type="button"
        class="btn btn-sm btn-success"
        data-bs-toggle="modal"
        data-bs-target="#publishModal-{{ processversion.pk }}">
  {% trans "publish"|capfirst %}
  <i class="fa fa-check"></i>
</button>

<div class="modal fade"
     id="publishModal-{{ processversion.pk }}"
     tabindex="-1"
     aria-labelledby="publishModalLabel"
     aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="publishModalLabel">{% blocktrans %}Publish {{processversion}}{% endblocktrans %}</h1>
        <button type="button"
                class="btn-close"
                data-bs-dismiss="modal"
                aria-label='{% trans "cancel"|capfirst %}'></button>
      </div>
      <div class="modal-body">{% blocktrans %}Are you sure you want to publish {{processversion}}?{% endblocktrans %}</div>
      <div class="modal-footer">
        <form action="{% url 'processversion_publish' processversion.pk %}"
              method="post">
          <input type='hidden' name='csrfmiddlewaretoken' value='{{ csrf_token }}' />
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans "cancel"|capfirst %}</button>
          <button type="submit" class="btn btn-success">{% trans "publish"|capfirst %}</button>
        </form>
      </div>
    </div>
  </div>
</div>